---
book_repo: pivotal-cf/docs-book-stemcell-rn
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'main'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: pivotal-cf/docs-stemcell-rn
    ref: 'master'
  directory: stemcells
  subnav_template: stemcell-subnav.erb
  product_info:
    use_local_header: true
    changelog_href: https://docs.pivotal.io/stemcells/
    local_header_img: /images/cloud_rings.png
    local_header_title: Ops Manager
    search_placeholder: Search Ops Manager Stemcell Release Notes
    url_prefix: stemcells
    local_header_links:
      - <a href="https://network.pivotal.io/products/stemcells-ubuntu-xenial/">Download from Tanzu Network</a>
      - <a href="https://community.pivotal.io/s/topic/0TO0P000000IKhwWAG/welcome">Knowledge Base</a>

- repository:
    name: pivotal-cf/docs-partials
    ref: main
  directory: pcf
  no_docs: true
